name: Sync File from Other Repo

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:   # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the CV
        run: |
          # Replace the URL and path as needed
          curl -o files/CV_NIU_Xuezhi.pdf https://github.com/n7729697/CV_NIU_Xuezhi/blob/main/CV_NIU_Xuezhi.pdf

      - name: Set remote URL with token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Commit and push changes if file updated
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add files/CV_NIU_Xuezhi.pdf
            git commit -m "Update file from source repository"
            git push origin master
          else
            echo "No changes detected."
          fi
